//! Compile-time-checked internationalization module.
//!
//! This module is generated by `leptos_i18n_build` from the JSON locale files
//! in `locales/`.  It re-exports the `Locale` enum (with `Locale::en` /
//! `Locale::de` variants), the `use_i18n()` hook, the `I18nContext`, and the
//! `t!` / `t_string!` / `td!` / `t_scope!` / `td_scope!` macros — all with
//! compile-time key checking.
//!
//! The generated file wraps everything in `pub mod i18n { … }`, so we include
//! it here and then re-export from the inner module.

include!(concat!(env!("OUT_DIR"), "/i18n/mod.rs"));

pub use self::i18n::*;
