name: Nested Garage uploader PR16 smoke

on:
  push:
    branches: [ci/test-trusted-garage-uploader]

permissions:
  actions: write
  contents: read
  id-token: write

cache-mode: write

jobs:
  merge:
    uses: codeandsolder/ci-workflows/.github/workflows/merge-sccache-l0.yml@8bc6c6241f60c6cd612742be337df788ed99415d
    with:
      source-run-id: "36735580654"
      source-event: push
